services:
  - docker

env:
  global:
    - DOCKER_ACCOUNT=sogis
    - DOCKER_REPO=geoserver

branches:
  only:
    - master

script:
  - docker build -t $DOCKER_ACCOUNT/$DOCKER_REPO:latest -t $DOCKER_ACCOUNT/$DOCKER_REPO:2.15.1 .

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin && docker push $DOCKER_ACCOUNT/$DOCKER_REPO
  on:
    branch: master
